version: "3"

services:
  backend:
    image: backend:0.1
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://kth-mysql:3306/local?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_DATA_MONGODB_URI: "mongodb://kth-mongodb:27017/local"
      SPRING_REDIS_HOST: "kth-redis"
      SPRING_REDIS_PORT: "6379"
    ports:
      - 8080:8080
    depends_on:
      - "kth-mongodb"
      - "kth-mysql"
      - "kth-redis"
    restart: always
    links:
      - kth-mongodb
    networks:
      - kth_network

  kth-mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "local"
      MYSQL_ROOT_HOST: "%"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    ports:
      - 3306:3306
    restart: always
    networks:
      - kth_network

  kth-redis:
    image: redis:6.2.6
    command: redis-server --port 6379
    ports:
      - 6379:6379
    restart: always
    networks:
      - kth_network

  kth-mongodb:
    image: mongo:5
    ports:
      - 27017:27017
    restart: always
    networks:
      - kth_network
    command: mongod

networks:
  kth_network:
    driver: bridge