spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      host: localhost
      port: 27017
      database: greendb
  datasource:
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3305/member?characterEncoding=UTF-8&serverTimezone=UTC

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secret: fUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
