spring:
  session:
    store-type: redis
  redis:
#    host: localhost
    host: myredis
    port: 6380
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: false
  data:
    mongodb:
#      uri: mongodb://localhost:27018/local
      uri: mongodb://mymongodb:27018/local


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#    url: jdbc:mysql://localhost:3306/local?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    url: jdbc:mysql://mysql:3306/local?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul


jwt:
  secret:
    key : fUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
